_wandb:
    value:
        cli_version: 0.28.0
        e:
            tp08y1zr2d9dbhauvmo91mccr2bqfbxn:
                codePath: Projects\phase-3-bountyhunter\train.py
                codePathLocal: train.py
                cpu_count: 4
                cpu_count_logical: 4
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "999057772544"
                        used: "457784430592"
                email: carljoshuamcoloma@gmail.com
                executable: C:\Python314\python.exe
                git:
                    commit: 3d27785b564afbd94f6eaa95e7cff61a91c46da8
                    remote: https://github.com/cdobby18/AI-Roadmap.git
                gpu: NVIDIA GeForce GTX 1050 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Pascal
                      cudaCores: 768
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce GTX 1050 Ti
                      uuid: GPU-20a35aa7-d4b6-bafe-b524-cc89a51adbec
                host: DESKTOP-PO21Q72
                memory:
                    total: "8530448384"
                os: Windows-10-10.0.19045-SP0
                program: D:\CJ\Documents\AI-Roadmap\Projects\phase-3-bountyhunter\train.py
                python: CPython 3.14.6
                root: D:\CJ\Documents\AI-Roadmap\Projects\phase-3-bountyhunter
                startedAt: "2026-07-17T04:24:34.713538Z"
                writerId: tp08y1zr2d9dbhauvmo91mccr2bqfbxn
        m: []
        python_version: 3.14.6
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 16
            "4": 3.14.6
            "5": 0.28.0
            "8":
                - 3
            "12": 0.28.0
            "13": windows-amd64
batch_size:
    value: 64
epochs:
    value: 100
hidden:
    value:
        - 64
        - 32
lr:
    value: 0.001
seed:
    value: 42
